import postgres from "postgres";
import { seedIfEmpty } from "./seed";

// Supabase Postgres via the postgres.js driver (pure JS — no native build step,
// runs on Cloudflare Workers under nodejs_compat). We talk to Supabase through
// its connection POOLER (Supavisor), so DATABASE_URL must be the pooler string
// (port 6543). Transaction-pooling mode forbids server-side prepared statements,
// hence `prepare: false`.
//
// In dev, Next.js hot-reloads modules; on Workers, module globals persist across
// requests within an isolate. Either way we cache the client + the one-time
// migrate/seed promise on globalThis so we don't reconnect or re-run setup per
// request.

export type Sql = ReturnType<typeof postgres>;

declare global {
  // eslint-disable-next-line no-var
  var __familyBrainSql: Sql | undefined;
  // eslint-disable-next-line no-var
  var __familyBrainReady: Promise<void> | undefined;
}

function createClient(): Sql {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error(
      "DATABASE_URL is not set. Add your Supabase POOLER connection string " +
        "(the one on port 6543) to .env — see .env.example."
    );
  }
  return postgres(url, {
    prepare: false, // required for Supabase's transaction pooler (Supavisor)
    max: 5,
    idle_timeout: 20,
    connect_timeout: 30,
  });
}

function getSql(): Sql {
  if (!global.__familyBrainSql) global.__familyBrainSql = createClient();
  return global.__familyBrainSql;
}

// Schema as discrete idempotent statements (run one-by-one rather than as one
// multi-statement blob, which the extended protocol won't accept). Postgres
// equivalents of the original SQLite schema:
//   - INTEGER PRIMARY KEY AUTOINCREMENT  -> INTEGER GENERATED BY DEFAULT AS IDENTITY
//   - datetime('now') default            -> to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
//     (kept as TEXT so created_at stays a string and sorts exactly as before)
const SCHEMA: string[] = [
  `CREATE TABLE IF NOT EXISTS members (
     id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name      TEXT NOT NULL,
     avatar    TEXT NOT NULL DEFAULT '🙂'
   )`,
  `CREATE TABLE IF NOT EXISTS spaces (
     id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     type             TEXT NOT NULL CHECK (type IN ('family','personal')),
     owner_member_id  INTEGER REFERENCES members(id) ON DELETE CASCADE
   )`,
  `CREATE TABLE IF NOT EXISTS memories (
     id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     space_id          INTEGER NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
     author_member_id  INTEGER REFERENCES members(id) ON DELETE SET NULL,
     title             TEXT NOT NULL,
     body              TEXT NOT NULL DEFAULT '',
     tags              TEXT NOT NULL DEFAULT '',
     created_at        TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
   )`,
  `CREATE TABLE IF NOT EXISTS personas (
     id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name           TEXT NOT NULL,
     avatar         TEXT NOT NULL DEFAULT '🤖',
     system_prompt  TEXT NOT NULL
   )`,
  `CREATE TABLE IF NOT EXISTS conversations (
     id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     member_id   INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
     persona_id  INTEGER REFERENCES personas(id) ON DELETE SET NULL,
     space_id    INTEGER REFERENCES spaces(id) ON DELETE SET NULL,
     created_at  TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
   )`,
  `CREATE TABLE IF NOT EXISTS messages (
     id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     conversation_id  INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
     role             TEXT NOT NULL CHECK (role IN ('system','user','assistant')),
     content          TEXT NOT NULL,
     model_used       TEXT,
     created_at       TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
   )`,
  `CREATE TABLE IF NOT EXISTS settings (
     id        INTEGER PRIMARY KEY CHECK (id = 1),
     provider  TEXT NOT NULL DEFAULT 'local',
     model     TEXT NOT NULL DEFAULT 'llama3.1',
     base_url  TEXT NOT NULL DEFAULT 'http://localhost:11434/v1'
   )`,
  // Security: Supabase auto-exposes the `public` schema through its REST "Data API"
  // (PostgREST), reachable with the public anon key. Enabling RLS — with NO policies —
  // default-denies the anon + authenticated roles, slamming that side-door shut so the
  // only way into the data is this app's privileged pooler connection. That connection
  // is the table OWNER, and owners bypass RLS, so the app is unaffected (privacy is also
  // still enforced in app code — see memories.ts). Idempotent, so it's safe on every
  // migrate. Do NOT add FORCE ROW LEVEL SECURITY: that would subject the owner connection
  // to RLS too and break the app.
  `ALTER TABLE members       ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE spaces        ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE memories      ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE personas      ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE conversations ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE messages      ENABLE ROW LEVEL SECURITY`,
  `ALTER TABLE settings      ENABLE ROW LEVEL SECURITY`,
];

async function migrate(sql: Sql): Promise<void> {
  for (const stmt of SCHEMA) await sql.unsafe(stmt);
}

/**
 * Ensure the schema exists and the demo data is seeded — exactly once per
 * isolate/process. Cached as a promise on globalThis; cleared on failure so a
 * later request can retry rather than being stuck with a rejected promise.
 */
export function ensureReady(): Promise<void> {
  if (!global.__familyBrainReady) {
    const sql = getSql();
    global.__familyBrainReady = (async () => {
      await migrate(sql);
      await seedIfEmpty(sql);
    })().catch((e) => {
      global.__familyBrainReady = undefined;
      throw e;
    });
  }
  return global.__familyBrainReady;
}

/** Get the ready (migrated + seeded) SQL client. Use this everywhere. */
export async function db(): Promise<Sql> {
  await ensureReady();
  return getSql();
}

/**
 * Run fn inside a real Postgres transaction. The callback receives a scoped
 * transaction client — use it for every statement that must commit together.
 */
export async function tx<T>(fn: (sql: Sql) => Promise<T>): Promise<T> {
  const sql = await db();
  return sql.begin(fn as never) as Promise<T>;
}
